name: Deploy prod with test by runner

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      - name: run tests
        run: mvn test
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy application.properties
        run: cp /home/domix/actions-runner/configs/application.properties /home/domix/actions-runner/_work/domix/domix/src/main/resources/
      - name: Stop
        run: docker compose down
      - name: Docker compose
        run: docker compose up -d --no-deps --build domix-back
